### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by dalethatcher** [jmcejuela/Scala-XML-Pretty-Printer#3]
Please specify the licence you are using for this code.

many thanks,

- Dale

**Comment by jmcejuela** [comment]
Thanks for the interest. I specified the Apache License v2.0 and moved the code to version 1.0.0 (semver).

**Comment by dalethatcher** [comment]
Perfect!  Thanks again...

**Comment by jmcejuela** [comment]
@dalethatcher No problem. Please star the repository ;)
